language: node_js
sudo: false
notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
      - tristan.wright@kitware.com
      - chris.harris@kitware.com
    on_success: change
    on_failure: always
cache:
  directories:
    - node_modules
node_js:
  - "4.1"
before_install:
  - npm run dep:travis
script:
  - npm run build:release
after_success:
  - npm run semantic-release
